sudo: required
services:
  - docker

before_install:
  - docker build -t jeykow/docker_react -f Dockerfile.dev .

script:
  - docker run jeykow/docker_react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-340948737027"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"